services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/env.docker
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80" # NGINX will serve frontend on port 80 inside container
    env_file:
      - ./frontend/env.docker
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
